name: SimpleExtras
main: me.odium.simpleextras.SimpleExtras
version: 0.8.1
commands:
   ranks:
      description: Return list of ranks from config
      permission:
      usage: /ranks
   basics:
      description: Return list of basics from config
      permission:
      usage: /basics
   owner:
      description: Reminds you of who the owner of the server is
      permission:
      usage: /owner
   website:
      description: Lists the servers webaddress
      permission:
      usage: /website
   creative:
      description: Change your gamemode to Creative
      permission: simpleextras.creative
      usage: /creative
   survival:
      description: Change your gamemode to Survival
      permission: simpleextras.survival
      usage: /survival
   boom:
      description: Creates a peaceful explosion on a player
      permission: simpleextras.boom
      usage: /boom [d/h/s] <playername>
   se:
      description: Help Menu
      permission:
      usage: /se
   exp:
      description: Awards a player the specified experience points
      permission: simpleextras.exp
      usage: /exp <player> <#>
   levelup:
      description: Raises a players experience level by the specified number
      permission: simpleextras.levelup
      usage: /levelup <player>
   levelset:
      description: Set a users experience level to the specified #
      permission: simpleextras.levelset
      usage: /levelset <player>
   levelget:
      description: View a users experience level
      permission: odiplugin.levelget
      usage: /levelget <player>
   bed:
      description: Returns a user to their bed spawn location
      permission: simpleextras.bed
      usage: /bed
   seen:
      description: Returns when the player was last seen on the server
      permission: simpleextras.seen
      usage: /seen <player>
   seenf:
      description: Returns when the player was first seen on the server
      permission: simpleextras.seen
      usage: /seenf <player>
   findplayer:
      description: Search all players who have joined the server
      permission: simpleextras.findplayer
      usage: /findplayer <part of playername>
   zoom:
      description: zoom in, up or down
      permission: simpleextras.zoom
      usage: /zoom [in/up/down] <# of blocks>
   fly:
      description: Enable/disable flight for a user
      permission: simpleextras.fly
      usage: /fly
   ignite:
      description: ignite a player
      permission: simpleextras.ignite
      usage: /ignite <playername>
   speed:
      description: give a player speed x2
      permission: simpleextras.speed
      usage: /speed <playername> [mins]
   blind:
      description: blind a player
      permission: simpleextras.blind
      usage: /blind <playername> [mins]
   jump:
      description: give a player jump x2
      permission: simpleextras.jump
      usage: /jump <playername> [mins]
   confuse:
      description: confuse a player
      permission: simpleextras.confuse
      usage: /confuse <playername> [mins]
   slow:
      description: slow a player
      permission: simpleextras.slow
      usage: /slow <playername> [mins]
   superdig:
      description: confuse a player
      permission: simpleextras.superdig
      usage: /superdig <playername> [mins]
   gf:
      description: fireball
      permission: simpleextras.fireball
      usage: /gf
   magic:
      description: magic text
      permission: simpleextras.magic
      usage: /magic <text>
   effects:
      description: player effects menu
      permission: simpleextras.effects
      usage: /effects