name: SimpleExtras
main: me.odium.simpleextras.SimpleExtras
version: 0.9.6
commands:
   ranks:
      description: Return list of ranks from config
      permission:
      usage: /ranks
   basics:
      description: Return list of basics from config
      permission:
      usage: /basics
   owner:
      description: Reminds you of who the owner of the server is
      permission:
      usage: /owner
   website:
      description: Lists the servers webaddress
      permission:
      usage: /website
   creative:
      description: Change your gamemode to Creative
      permission: simpleextras.creative
      usage: /creative
   survival:
      description: Change your gamemode to Survival
      permission: simpleextras.survival
      usage: /survival
   boom:
      description: Creates a peaceful explosion on a player
      permission: simpleextras.boom
      usage: /boom [d/h/s] <playername>
   se:
      aliases: [SimpleExtras]
      description: Help Menu
      permission:
      usage: /se
   exp:
      aliases: [xp]
      description: Awards a player the specified experience points
      permission: simpleextras.exp
      usage: /exp <player> <#>
   levelup:
      description: Raises a players experience level by the specified number
      permission: simpleextras.levelup
      usage: /levelup <player>
   levelset:
      description: Set a users experience level to the specified #
      permission: simpleextras.levelset
      usage: /levelset <player>
   levelget:
      description: View a users experience level
      permission: simpleextras.levelget
      usage: /levelget <player>
   bed:
      description: Returns a user to their bed spawn location
      permission: simpleextras.bed
      usage: /bed
   seen:
      description: Returns when the player was last seen on the server
      permission: simpleextras.seen
      usage: /seen <player>
   seenfirst:
      aliases: [seenf]
      description: Returns when the player was first seen on the server
      permission: simpleextras.seen
      usage: /seenf <player>
   findplayer:
      description: Search all players who have joined the server
      permission: simpleextras.findplayer
      usage: /findplayer <part of playername>
   zoom:
      description: zoom in, up or down
      permission: simpleextras.zoom
      usage: /zoom
   fly:
      description: Enable/disable flight for a user
      permission: simpleextras.fly
      usage: /fly
   ignite:
      description: ignite a player
      permission: simpleextras.ignite
      usage: /ignite <playername>
   speed:
      description: give a player speed x2
      permission: simpleextras.speed
      usage: /speed [playername] [mins]
   blind:
      description: blind a player
      permission: simpleextras.blind
      usage: /blind [playername] [mins]
   jump:
      description: give a player jump x2
      permission: simpleextras.jump
      usage: /jump [playername] [mins]
   confuse:
      description: confuse a player
      permission: simpleextras.confuse
      usage: /confuse [playername] [mins]
   slow:
      description: slow a player
      permission: simpleextras.slow
      usage: /slow [playername] [mins]
   slowdig:
      description: slow a players digging
      permission: simpleextras.slowdig
      usage: /slow [playername] [mins]
   fireresistance:
      aliases: [fireresist]
      description: give a player fire resist
      permission: simpleextras.fireresist
      usage: /slow [playername] [mins]
   superdig:
      description: confuse a player
      permission: simpleextras.superdig
      usage: /superdig [playername] [mins]
   waterbreathing:
      description: Grant a player Water Breathing
      permission: simpleextras.waterbreathing
      usage: /waterbreathing [playername] [mins]
   invisible:
      description: Grant a player invisibility
      permission: simpleextras.invisible
      usage: /invisible [playername] [mins]
   nightvision:
      description: Grant a player Night Vision
      permission: simpleextras.nightvision
      usage: /nightvision [playername] [mins]
   hunger:
      description: Make a player hungry
      permission: simpleextras.hunger
      usage: /hunger [playername] [mins]
   weakness:
      description: Make a player weak
      permission: simpleextras.weakness
      usage: /weakness [playername] [mins]
   strength:
      description: Make a player stronger
      permission: simpleextras.strength
      usage: /strength [playername] [mins]
   regeneration:
      description: Grant a player regeneration
      permission: simpleextras.regeneration
      usage: /regeneration [playername] [mins]
   poison:
      description: Poison a player
      permission: simpleextras.poison
      usage: /poison [playername] [mins]
   gf:
      description: fireball
      permission: simpleextras.fireball
      usage: /gf
   effects:
      description: player effects menu
      permission: simpleextras.effects
      usage: /effects
   admin:
      description: Lists the server admins
      permission: simpleextras.listadmin
      usage: /admin
   tpb:
      description: Teleport with a flourish
      permission: simpleextras.tpb
      usage: /tpb [gl] <player>
   home:
      description: Teleport to a saved home location
      permission: simpleextras.home
      usage: /home
   sethome:
      description: Save your home location
      permission: simpleextras.sethome
      usage: /sethome [player]
   mobattack:
      description: cause hostile mobs to target a player
      permission: simpleextras.mobattack
      usage: /mobattack menu
   flame:
      aliases: [flames]
      description: Dancing flames for your player model
      permission: simpleextras.flame
      usage: /flame [on/off] [player]
   noeffect:
      description: Remove all effects from a player
      permission: simpleextras.noeffect
      usage: /noeffect [player]
   grow:
      description: Grow saplings in front of player
      permission: simpleextras.grow
      usage: /grow
   grenade:
      description: Toggle snowball grenades
      permission: simpleextras.grenade
      usage: /grenade [-d] [user]
   missile:
      description: Toggle arrow missiles
      permission: simpleextras.missile
      usage: /missile [-d] [user]
   colours:
      aliases: [colors]
      description: Return colour codes
      permission: simpleextras.colourcodes
      usage: /colours